version: '3'
services:
  front-end:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_DB_USER=${DB_USER}
      - MONDO_DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_PORT}:3000"
    networks:
      - appnet
  auth:
    build:
      context: ./auth/
      dockerfile: Dockerfile
    command: jwtServer
    volumes:
      - /private/var/log/jwtserver/:/var/log/jwtserver
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - TIM_PASSWORD=${TIM_PASSWORD}
      - LOG_PATH=${AUTH_LOG_PATH}
    ports: 
      - "${AUTH_PORT}:3001"
    networks:
      - appnet
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "${REDIS_PORT}:6379"
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "${API_PORT}:5000"
    networks:
      - appnet
    environment:
      - REDIS_URL=redis://cache
      - REDIS_PORT=${REDIS_PORT}
networks:
  appnet:
    driver: bridge

