version: '3'
services:
  front-end:
    build:
      context: ./front-end/
      dockerfile: Dockerfile-prod
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_DB_USER=${DB_USER}
      - MONDO_DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_HOST_PORT}:${APP_CONT_PORT}"
    networks:
      - appnet
  auth:
    build:
      context: ./auth/
      dockerfile: Dockerfile
    command: jwtServer
    volumes:
      - ./auth_logs:/var/log/jwtserver
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - TIM_PASSWORD=${TIM_PASSWORD}
      - LOG_PATH=${AUTH_LOG_PATH}
    ports: 
      - "${AUTH_HOST_PORT}:${AUTH_CONT_PORT}"
    networks:
      - appnet
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "${API_HOST_PORT}:${API_CONT_PORT}"
    networks:
      - appnet
    environment:
      - AUTH_URL=auth:${AUTH_CONT_PORT}
      - STORAGE_URL=storage:${STORAGE_CONT_PORT}
  storage:
    build:
      context: ./storage/
      dockerfile: Dockerfile
    ports:
      - "${STORAGE_HOST_PORT}:${STORAGE_CONT_PORT}"
    networks:
      - appnet
    environment:
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - LOG_PATH=${STORAGE_LOG_PATH}
networks:
  appnet:
    driver: bridge

