version: '3'
services:
  front-end:
    build:
      context: ./front-end/
    command: npm start
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    ports:
      - '8000:3000'