# build environment
FROM node:12.2.0-alpine as build
WORKDIR /usr/app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
COPY conf/* ./conf
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . .
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html

RUN rm -rf /etc/nginx/conf.d
COPY --from=build /usr/app/conf /etc/nginx
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]